import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'features/catalogs/views/catalogs_page.dart';
import 'features/catalogs/views/brand_detail_page.dart';
import 'features/inventory/views/inventory_page.dart';
import 'features/diary/views/diary_page.dart';
import 'features/memos/views/memos_page.dart';
import 'features/catalogs/views/razors_page.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const WskbApp());
}

/// Root app with GoRouter
class WskbApp extends StatelessWidget {
  const WskbApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'WSKB',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: const Color(0xFF2962FF),
      ),
      routerConfig: appRouter,
    );
  }
}

/* ----------------------- Router ----------------------- */

final appRouter = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder: (ctx, st) => const AppShell(),
      routes: [
	GoRoute(
  	  path: 'memos',
  	  builder: (ctx, st) => const MemosPage(ownerUserId: 'local'),
	),

        GoRoute(
          path: 'razors',
          builder: (ctx, st) => const RazorsPage(),
        ),

        GoRoute(
          path: 'brand/:id',
          builder: (ctx, st) => BrandDetailPage(
            brandId: st.pathParameters['id']!,
          ),
        ),
        GoRoute(
          path: 'about',
          builder: (ctx, st) => const AboutPage(),
        ),
      ],
    ),
  ],
);

/* ----------------------- Shell ------------------------ */

class AppShell extends StatefulWidget {
  const AppShell({super.key});
  @override
  State<AppShell> createState() => _AppShellState();
}

class _AppShellState extends State<AppShell> {
  int index = 0;
  final pages = const [CatalogsPage(), InventoryPage(), DiaryPage()];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
  	title: const Text('WSKB'),
  	actions: [
   	 IconButton(
      		tooltip: 'Personal Memos',
      		icon: const Icon(Icons.note_alt_outlined),
     		 // use push so the back button appears
     		 onPressed: () => context.push('/memos'),
    	 ),
    	 IconButton(
     		 tooltip: 'About',
     		 icon: const Icon(Icons.info_outline),
      		 onPressed: () => context.push('/about'),
   	 ),
  	],
      ),

      body: IndexedStack(index: index, children: pages),
      bottomNavigationBar: NavigationBar(
        selectedIndex: index,
        onDestinationSelected: (i) => setState(() => index = i),
        destinations: const [
          NavigationDestination(icon: Icon(Icons.library_books), label: 'Catalogs'),
          NavigationDestination(icon: Icon(Icons.inventory_2), label: 'Inventory'),
          NavigationDestination(icon: Icon(Icons.event_note), label: 'Diary'),
        ],
      ),
    );
  }
}

/* ----------------------- About ------------------------ */

class AboutPage extends StatelessWidget {
  const AboutPage({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('About')),
      body: const Center(
        child: Text('This is a clean Flutter starter with GoRouter and tabs.'),
      ),
    );
  }
}
